# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1

      - name: Run Nightly Test
        run: |
          # Example of MATLAB working correctly
          matlab -nosplash -nojvm -logfile "matlabVersionLog.cmaketmp" -nodesktop -nodisplay -batch "version, exit"
          ls $HOME/.matlab
          ls $HOME/.matlab/R2022a_licenses
